### ISSUE TITLE
Always getting a "Error while initialize or login process"

### ISSUE THREAD

**Issue by zImPatrick** [SzymonLisowiec/node-epicgames-client#83]
While logging in I always get the message "Error while initialize or login process"

```
(node:23416) UnhandledPromiseRejectionWarning: Error: Error while initialize or login process.
    at Object.exports.login ([path]\epic.js:7:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My code:
```
const { Launcher } = require('epicgames-client');

const launcher = new Launcher({ email: "email", password: "pass" });

exports.login = async (email, password) => {
    if(!await launcher.init() || !await launcher.login()) {
      throw new Error('Error while initialize or login process.');
    }
    
    console.log(`Logged in as ${launcher.account.name}`);
};
```

Also, is there any way to get more information on why it failed or something?

**Comment by gebederry** [comment]
The same as mine :(

**Comment by zImPatrick** [comment]
Okay, [kekistanzalt's pull request](https://github.com/SzymonLisowiec/node-epicgames-client/pull/82) helped. That asked for the exchange code and I could log in with that.
Would still like it being merged at some point, so I will leave this open for the time

**Comment by SzymonLisowiec** [comment]
This is due to asking for fill the captcha. Please read more here: https://epicgames-client.kysune.me/Client.html#login-options

[kekistanzalt's pull request](https://github.com/SzymonLisowiec/node-epicgames-client/pull/82) this PR have wrong approach to this subject and is ignoring `resolveCaptcha` method. Unfortunately at the moment isn't possible to easy solve captcha e.g. through link to captcha, because FunCaptcha is probably checking domain and browser fingerprint.

At the moment I can only add remembering a session feature in near future. But the captcha will still have to be solve while first login.

**Comment by SzymonLisowiec** [comment]
Version [`2.0.23`](https://github.com/SzymonLisowiec/node-epicgames-client/commit/ef2c219cf2a7f6df88c1cfc4ec3a488f315ecaf2) allows use `exchangeCode` to login instead account's credentials. Read more [here](https://epicgames-client.kysune.me/Client.html#login-options-exchangecode).

I think this issue can be closed.
